ci:
  skip:
    - eslint
    - prettier
    - go-fmt
    - go-vet
    - go-tidy
    - golangci-lint-full
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.20.0
    hooks:
      - id: zizmor
        args:
          - --fix=all
  - repo: https://github.com/jvllmr/pre-commit-prettier
    rev: v3.7.4
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@latest
          - prettier-plugin-organize-imports@latest
  - repo: https://github.com/segmentio/golines
    rev: v0.13.0
    hooks:
      - id: golines
  - repo: https://github.com/golangci/golangci-lint/
    rev: v2.8.0
    hooks:
      - id: golangci-lint-full
  - repo: local
    hooks:
      - id: eslint
        name: lint typescript
        entry: pnpm eslint
        language: system
        pass_filenames: true
        types_or:
          - ts
          - tsx
      - id: go-fmt
        name: go fmt
        entry: go fmt
        language: system
        pass_filenames: false
        types:
          - go
      - id: go-vet
        name: go vet
        entry: go vet
        language: system
        pass_filenames: false
        always_run: true
      - id: go-tidy
        name: tidy go mod
        entry: go mod tidy
        language: system
        pass_filenames: false
        types_or:
          - go-sum
          - go-mod
