name: frans_dev

services:
  keycloak-db:
    container_name: frans_dev_keycloak_db
    image: docker.io/postgres:18
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secret
    volumes:
      - keycloak-db-data:/var/lib/postgresql/18/docker
    networks:
      - keycloak
  keycloak:
    container_name: frans_dev_keycloak
    image: quay.io/keycloak/keycloak:26.4.6
    command: start-dev --import-realm --verbose
    ports:
      - 127.0.0.1:8080:8080
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
    networks:
      - keycloak
    volumes:
      - ./keycloak/realm_import:/opt/keycloak/data/import:Z
  smtp:
    container_name: frans_dev_smtp
    image: docker.io/rnwood/smtp4dev:3.10.3
    ports:
      - 127.0.0.1:5000:80
      - 127.0.0.1:2525:25
  openobserve:
    container_name: frans_dev_openobserve
    image: public.ecr.aws/zinclabs/openobserve:v0.16.3
    environment:
      ZO_ROOT_USER_EMAIL: "root@example.com"
      ZO_ROOT_USER_PASSWORD: "admin"
      ZO_ROOT_USER_TOKEN: "admin"
    ports:
      - "127.0.0.1:5080:5080"
      - "127.0.0.1:5081:5081"
    volumes:
      - o2-data:/data

volumes:
  keycloak-db-data:
  o2-data:

networks:
  keycloak:
