name: Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    permissions:
      contents: read
    name: unittest
    runs-on: ubuntu-latest
    services:
      smtp:
        image: docker.io/rnwood/smtp4dev:3.11.0
        ports:
          - 127.0.0.1:2525:25
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ">=1.25.5"
      - name: Run pre-build steps
        run: ./scripts/prebuild.sh
      - name: Generate version
        run: ./scripts/gen_version.sh
      - name: Run tests
        run: pnpm test:cover
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  build:
    permissions:
      contents: read
    name: test-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          run_install: false
      - name: Install Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 24.11.1
          cache: "pnpm"
      - name: Setup go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ">=1.25.5"
      - name: Install dependencies
        run: pnpm install --frozen-lock
      - name: Build
        run: pnpm build
      - name: Upload build
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: build-output
          path: frans
  migration-sqlite:
    needs: build
    permissions:
      contents: read
    name: test-migration-sqlite3
    runs-on: ubuntu-latest
    env:
      FRANS_DB_TYPE: sqlite3

    steps:
      - name: Download artifact from build workflow
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: build-output
      - run: chmod +x frans
      - name: Run migration
        run: ./frans migrate
  migration-postgres:
    needs: build
    permissions:
      contents: read
    name: test-migration-postgres
    runs-on: ubuntu-latest
    env:
      FRANS_DB_TYPE: postgres
      FRANS_DB_HOST: localhost
      FRANS_DB_USER: postgres
      FRANS_DB_PASSWORD: postgres
      FRANS_DB_NAME: postgres

    services:
      postgres:
        image: docker.io/postgres:18-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Download artifact from build workflow
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: build-output
      - run: chmod +x frans
      - name: Run migration
        run: ./frans migrate
  migration-mysql:
    needs: build
    permissions:
      contents: read
    name: test-migration-mysql
    runs-on: ubuntu-latest
    env:
      FRANS_DB_TYPE: mysql
      FRANS_DB_HOST: localhost
      FRANS_DB_USER: user
      FRANS_DB_PASSWORD: abc123
      FRANS_DB_NAME: frans

    services:
      mysql:
        image: docker.io/mysql:9
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_USER: user
          MYSQL_PASSWORD: abc123
          MYSQL_DATABASE: frans
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Download artifact from build workflow
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
        with:
          name: build-output
      - run: chmod +x frans
      - name: Run migration
        run: ./frans migrate
