apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "frans.fullname" . }}-lifecycle-files
  labels:
    {{- include "frans.labels" . | nindent 4 }}
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.cronjobs.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjobs.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          initContainers:
            - name: {{ include "frans.fullname" . }}-lifecycle-files-migrate
              {{- with .Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - migrate
              resources:
                {{- toYaml .Values.cronjobs.resources | nindent 16 }}
              volumeMounts:
                - name: config
                  mountPath: /opt/frans/frans.yaml
                  subPath: frans.yaml
              {{- with .Values.volumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
              {{- if .Values.db.type }}
                - name: FRANS_DB_TYPE
                  value: {{ .Values.db.type }}
              {{- end }}
              {{- if .Values.db.host }}
                - name: FRANS_DB_HOST
                  value: {{ .Values.db.host }}
              {{- end }}
              {{- if .Values.db.port | quote }}
                - name: FRANS_DB_PORT
                  value: {{ .Values.db.port | quote }}
              {{- end }}
              {{- if .Values.db.name }}
                - name: FRANS_DB_NAME
                  value: {{ .Values.db.name }}
              {{- end }}
              {{- if .Values.db.user }}
                - name: FRANS_DB_USER
                  value: {{ .Values.db.user }}
              {{- end }}
              {{- if .Values.db.password }}
                - name: FRANS_DB_PASSWORD
                  value: {{ .Values.db.password }}
              {{- end }}
          containers:
            - name: {{ include "frans.fullname" . }}-lifecycle-files
              {{- with .Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion}}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                - task
                - lifecycle-file
              resources:
                {{- toYaml .Values.cronjobs.resources | nindent 16 }}
              volumeMounts:
                - name: config
                  mountPath: /opt/frans/frans.yaml
                  subPath: frans.yaml
              {{- with .Values.volumeMounts }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
              {{- if .Values.db.type }}
                - name: FRANS_DB_TYPE
                  value: {{ .Values.db.type }}
              {{- end }}
              {{- if .Values.db.host }}
                - name: FRANS_DB_HOST
                  value: {{ .Values.db.host }}
              {{- end }}
              {{- if .Values.db.port }}
                - name: FRANS_DB_PORT
                  value: {{ .Values.db.port | quote }}
              {{- end }}
              {{- if .Values.db.name }}
                - name: FRANS_DB_NAME
                  value: {{ .Values.db.name }}
              {{- end }}
              {{- if .Values.db.user }}
                - name: FRANS_DB_USER
                  value: {{ .Values.db.user }}
              {{- end }}
              {{- if .Values.db.password }}
                - name: FRANS_DB_PASSWORD
                  value: {{ .Values.db.password }}
              {{- end }}
              {{- if .Values.extraEnv }}
                {{- toYaml .Values.extraEnv | nindent 16 }}
              {{- end }}
          volumes:
            - name: config
              configMap:
                name: {{ include "frans.fullname" . }}
                items:
                  - key: frans.yaml
                    path: frans.yaml
          {{- with .Values.volumes }}
            {{- toYaml . | nindent 12 }}
          {{- end }}